import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { formatMoney, formatDate } from "@/lib/utils";
import { ApprovalRow } from "@/components/approval-row";

export default async function ApprovalsPage() {
  const supabase = await createClient();
  const { data: invoices } = await supabase
    .from("invoices")
    .select("id, invoice_number, total, due_date, bill_to_company, bill_to_email, issue_date, service_plan_id")
    .eq("status", "pending_approval")
    .order("due_date");

  return (
    <div>
      <div className="mb-6">
        <h1 className="display text-4xl">Approvals</h1>
        <p className="text-fm-muted">Recurring drafts auto-generated by cron. Review and approve to send.</p>
      </div>

      {!invoices || invoices.length === 0 ? (
        <div className="card text-center py-16">
          <p className="text-fm-muted">Nothing pending approval. ✓</p>
          <Link href="/admin/plans" className="text-sm font-semibold text-fm-ink hover:underline mt-3 inline-block">View service plans →</Link>
        </div>
      ) : (
        <div className="space-y-3">
          {invoices.map((inv) => (
            <ApprovalRow
              key={inv.id}
              invoice={inv as any}
            />
          ))}
        </div>
      )}
    </div>
  );
}
