-- ============================================================
-- Filter Monkey Invoicing — Initial schema
-- Single-tenant: all rows owned by auth.uid() of the configured owner.
-- RLS is on for every table; only the owner email (set in app/middleware) sees data.
-- ============================================================

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- ---------- enums ----------
create type invoice_status as enum (
  'draft',             -- being edited in admin
  'pending_approval',  -- auto-generated by recurring cron, awaiting owner approve
  'sent',              -- emailed to client, awaiting payment
  'paid',
  'overdue',
  'void'
);

create type payment_method as enum ('check', 'stripe', 'cash', 'ach', 'other');

create type plan_frequency as enum ('monthly', 'quarterly', 'semiannual', 'annual', 'custom_days');

-- ---------- core tables ----------

create table customers (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  company_name    text not null,
  contact_name    text,
  email           text,
  phone           text,
  -- billing address (separate from service location)
  billing_line1   text,
  billing_line2   text,
  billing_city    text,
  billing_state   text,
  billing_postal  text,
  payment_terms_days  integer not null default 15,
  default_payment_method payment_method not null default 'check',
  notes           text,
  archived        boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index customers_owner_idx on customers(owner_id);
create index customers_company_idx on customers(company_name);

create table locations (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  customer_id     uuid not null references customers(id) on delete cascade,
  label           text not null,            -- "Main Office", "Building A", etc.
  line1           text,
  line2           text,
  city            text,
  state           text,
  postal          text,
  access_notes    text,                     -- gate code, key location, contact on site, etc.
  archived        boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index locations_customer_idx on locations(customer_id);
create index locations_owner_idx on locations(owner_id);

-- catalog of filter SKUs (reusable across customers/locations)
create table filter_skus (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  sku             text,                     -- internal sku/code, optional
  name            text not null,            -- "16x20x1 MERV 8 Pleated"
  size            text,                     -- "16x20x1"
  merv            integer,
  brand           text,
  unit_price      numeric(10,2) not null default 0,
  unit_cost       numeric(10,2),            -- your cost — for margin tracking, hidden on invoice
  description     text,
  archived        boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index filter_skus_owner_idx on filter_skus(owner_id);

-- per-location filter mix: how many of each SKU at this location
create table location_filters (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  location_id     uuid not null references locations(id) on delete cascade,
  sku_id          uuid not null references filter_skus(id) on delete restrict,
  quantity        integer not null default 1 check (quantity > 0),
  unit_price_override numeric(10,2),       -- override SKU unit_price for this location, optional
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique(location_id, sku_id)
);
create index location_filters_location_idx on location_filters(location_id);

-- recurring service plans
create table service_plans (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  customer_id     uuid not null references customers(id) on delete cascade,
  name            text not null,            -- "Quarterly filter service"
  frequency       plan_frequency not null,
  custom_interval_days integer,             -- only used if frequency = custom_days
  -- which locations this plan covers (null/empty = ALL locations of customer)
  location_ids    uuid[] not null default '{}',
  -- optional flat labor / visit fee added to every generated invoice
  labor_fee       numeric(10,2) not null default 0,
  labor_fee_label text,                     -- "Service visit (1hr)"
  -- when to generate the draft: N days before due date
  lead_time_days  integer not null default 7,
  next_due_date   date not null,
  payment_terms_days integer,               -- override customer terms; null = use customer's
  active          boolean not null default true,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index service_plans_owner_idx on service_plans(owner_id);
create index service_plans_next_due_idx on service_plans(next_due_date) where active;

-- invoices
create table invoices (
  id                uuid primary key default uuid_generate_v4(),
  owner_id          uuid not null references auth.users(id) on delete cascade,
  customer_id       uuid not null references customers(id) on delete restrict,
  service_plan_id   uuid references service_plans(id) on delete set null,
  invoice_number    text not null,             -- human ref e.g. FM-2026-0001
  status            invoice_status not null default 'draft',
  issue_date        date not null default current_date,
  due_date          date not null,
  -- snapshot fields — copied at issue so customer renames/etc don't rewrite history
  bill_to_company   text not null,
  bill_to_contact   text,
  bill_to_email     text,
  bill_to_address   text,                      -- pre-formatted multi-line address
  -- totals (also denormalized; line items are the source of truth)
  subtotal          numeric(10,2) not null default 0,
  tax               numeric(10,2) not null default 0,
  total             numeric(10,2) not null default 0,
  amount_paid       numeric(10,2) not null default 0,
  balance_due       numeric(10,2) generated always as (total - amount_paid) stored,
  -- content
  notes             text,
  payment_terms     text,                      -- snapshot e.g. "Net 15"
  check_instructions text,                     -- snapshot of where to mail checks
  -- public access tokens (used for /sign and /pay public links)
  public_token      text not null unique default encode(gen_random_bytes(24), 'hex'),
  -- email tracking
  sent_at           timestamptz,
  last_email_id     text,
  -- signature
  signed_at         timestamptz,
  signature_id      uuid,                      -- FK set after signature row created
  -- pdf
  pdf_storage_path  text,                      -- supabase storage key
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create unique index invoices_owner_number_idx on invoices(owner_id, invoice_number);
create index invoices_customer_idx on invoices(customer_id);
create index invoices_status_idx on invoices(status);
create index invoices_due_date_idx on invoices(due_date);

create table invoice_line_items (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  invoice_id      uuid not null references invoices(id) on delete cascade,
  -- snapshot from sku/location_filters at time of generation
  sku_id          uuid references filter_skus(id) on delete set null,
  location_id     uuid references locations(id) on delete set null,
  description     text not null,             -- "16x20x1 MERV 8 — Building A"
  quantity        numeric(10,2) not null default 1,
  unit_price      numeric(10,2) not null default 0,
  line_total      numeric(10,2) generated always as (quantity * unit_price) stored,
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now()
);
create index line_items_invoice_idx on invoice_line_items(invoice_id);

create table payments (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  invoice_id      uuid not null references invoices(id) on delete cascade,
  amount          numeric(10,2) not null check (amount > 0),
  method          payment_method not null,
  paid_at         date not null default current_date,
  -- check-specific
  check_number    text,
  deposit_date    date,
  -- stripe-specific
  stripe_session_id  text,
  stripe_payment_intent_id text,
  -- generic
  notes           text,
  created_at      timestamptz not null default now()
);
create index payments_invoice_idx on payments(invoice_id);

create table signatures (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  invoice_id      uuid not null references invoices(id) on delete cascade,
  signer_name     text,
  signer_title    text,
  signature_storage_path text not null,    -- PNG in supabase storage
  ip_address      inet,
  user_agent      text,
  signed_at       timestamptz not null default now()
);
create index signatures_invoice_idx on signatures(invoice_id);

create table email_log (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references auth.users(id) on delete cascade,
  invoice_id      uuid references invoices(id) on delete set null,
  kind            text not null,           -- "invoice_sent", "receipt", "signature_confirm", "approval_pending"
  to_email        text not null,
  subject         text,
  resend_id       text,
  status          text,                    -- "sent", "delivered", "failed", "bounced"
  error           text,
  sent_at         timestamptz not null default now()
);
create index email_log_invoice_idx on email_log(invoice_id);

-- single-row-per-owner runtime settings (branding, payment instructions, etc.)
create table settings (
  owner_id        uuid primary key references auth.users(id) on delete cascade,
  business_name   text,
  logo_url        text,
  business_address text,
  business_phone  text,
  business_email  text,
  email_signature text,
  pdf_accent_color text,                     -- hex e.g. "#FFD60A"
  default_terms_days integer not null default 15,
  invoice_number_prefix text not null default 'FM',
  invoice_number_seq    integer not null default 0,
  check_instructions text,
  stripe_enabled  boolean not null default false,
  resend_from_email text,
  updated_at      timestamptz not null default now()
);

-- ---------- updated_at triggers ----------
create or replace function set_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

do $$ declare t text;
begin
  for t in select unnest(array['customers','locations','filter_skus','location_filters','service_plans','invoices','settings']) loop
    execute format('create trigger %I_set_updated before update on %I for each row execute function set_updated_at();', t || '_uat', t);
  end loop;
end $$;

-- ---------- RLS ----------
alter table customers          enable row level security;
alter table locations          enable row level security;
alter table filter_skus        enable row level security;
alter table location_filters   enable row level security;
alter table service_plans      enable row level security;
alter table invoices           enable row level security;
alter table invoice_line_items enable row level security;
alter table payments           enable row level security;
alter table signatures         enable row level security;
alter table email_log          enable row level security;
alter table settings           enable row level security;

-- "owner-only" policies for every table — auth.uid() must match owner_id
do $$ declare t text;
begin
  for t in select unnest(array[
    'customers','locations','filter_skus','location_filters','service_plans',
    'invoices','invoice_line_items','payments','signatures','email_log','settings'
  ]) loop
    execute format($f$
      create policy %I on %I for all
        to authenticated
        using (owner_id = auth.uid())
        with check (owner_id = auth.uid());
    $f$, t || '_owner_all', t);
  end loop;
end $$;

-- Public token-based access (for /sign/[token] and /pay/[token]) is performed
-- via service_role from a Next.js Route Handler — RLS bypassed there. We do NOT
-- expose anon SELECT on invoices.

-- ---------- storage buckets ----------
-- Run in Supabase SQL editor or via dashboard:
--   insert into storage.buckets (id, name, public) values ('invoices','invoices',false) on conflict do nothing;
--   insert into storage.buckets (id, name, public) values ('signatures','signatures',false) on conflict do nothing;
--   insert into storage.buckets (id, name, public) values ('logos','logos',true) on conflict do nothing;
